### ISSUE TITLE
Reads error !

### ISSUE THREAD

**Issue by jnarayan81** [kakitone/MetaFinisherSC#3]
python -m srcRefactor.misassemblyFixerLib.mFixer -par 10 /scratch/unamur/URBE/jnarayan/testDATA/ /tmp/MUMmer3.23/

The script terminated with following error: 

```
Traceback (most recent call last):
  File "/home/unamur/URBE/jnarayan/python/Python-2.7.11/Lib/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/unamur/URBE/jnarayan/python/Python-2.7.11/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/users/j/n/jnarayan/MetaFinisherSC/srcRefactor/misassemblyFixerLib/mFixer.py", line 64, in <module>
    merger.mainFlow(newFolderName, newMummerLink)
  File "srcRefactor/misassemblyFixerLib/merger.py", line 958, in mainFlow
    onlyLRMiassemblyFix(newFolderName, newMummerLink, filterName)
  File "srcRefactor/misassemblyFixerLib/merger.py", line 765, in onlyLRMiassemblyFix  
    alignSR2LC(folderName, mummerLink, inputName)
  File "srcRefactor/misassemblyFixerLib/merger.py", line 182, in alignSR2LC
    if completelyEmbedSR2TR(eachsub, SRLenDic) :
  File "srcRefactor/misassemblyFixerLib/merger.py", line 119, in completelyEmbedSR2TR 
    readLen = lenDic[readName]
KeyError: 'm161222_145955_42202_c101053792550000001823239812291634_s1_p0_100000_3544_14682'
```

How to fix it ?

**Comment by jnarayan81** [comment]
It was resolved by one-liner provided by the authors 
```
    perl -pe 's/>[^\$]*$/">Seg" . ++$n ."\n"/ge' LR.fasta > newLR.fasta
    cp newLR.fasta LR.fasta
    perl -pe 's/>[^\$]*$/">Seg" . ++$n ."\n"/ge' LC.fasta > newLC.fasta
    cp newLC.fasta LC.fasta
```
